### PR TITLE
[UI/UX] change spinner to avoid confusion about completion status

### PR DESCRIPTION
**Pull request by alejandroEsc**
**What this PR does / why we need it**:
Suggest to change out spinner as current one gives the impression that it will terminate when reaching the end, false impression of progression. Spinning does NOT give this perception and so less likely to cause confusion.

character set 7 chosen, minor change.
see https://github.com/briandowns/spinner

**Special notes for your reviewer**:

**Release note**:

```
Spinner changed to avoid impression of completion status
```

### CODE REVIEW

**Comment by alejandroEsc** [comment]
@coffeepac @joejulian  would like this reviewed please.

**Comment by alejandroEsc** [comment]
@davidewatson @guineveresaenger @DStorck  You guys have opinions on this?

**Comment by guineveresaenger** [comment]
I like it.

**Comment by davidewatson** [comment]
I dislike the character set, but let's see.

**Pull request merged**
