### PR TITLE
[wip] Rkt integ Into Kraken.

### PR DESCRIPTION
**Pull request by mikeln**
Should work transparently.  I.e. you should not have to add extra vars in your setup for "regular" docker.

However, have NOT been able tot get rkt to run correctly yet.  Still analyzing issues.  But those don't seem to have anything to do with this kraken standup.

Initial PR add, probably more coming, as RKT get working again

### CODE REVIEW

**Comment by mikeln** [comment]
retest this please

**Comment by mikeln** [comment]
Need to rebase the new ansible changes.

**Comment by davidewatson** [comment]
We should consider using the terraform modules concept to add rkt support [1] since it is not an AWS specific feature.

[1] https://opencredo.com/terraform-infrastructure-design-patterns/

**Comment by maratoid** [comment]
It does not seem like we will be merging this into kraken 1. Rkt support is in K2 though.

**Pull request closed without merging**
