### PR TITLE
remove the leading v

### PR DESCRIPTION
**Pull request by coffeepac**
**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
```

### CODE REVIEW

**Comment by davidewatson** [comment]
`kraken-lib` releases all have a leading v in their versions, and `kraken` used to. While not strictly semver, this convention has been cut and pasted into all other solas derived repositories. It has also crept into our config (e.g. `kubeConfig.version`). Do we want to let `kraken` be the oddball?

**Comment by philoserf** [comment]
i think the leading _v_ has more community uptake than bare version numbers

**Comment by leahnp** [comment]
I don't care either way, but I think all our projects should follow the same convention.

**Comment by philoserf** [comment]
we have quite a few competing  _conventions_  don't we

**Comment by coffeepac** [comment]
formal documentation for kraken always had a bare version number.  The leading 'v' are from pre-history (ie:  before common-tools existed)

**Comment by leahnp** [comment]
Should we merge this and create an issue for changing all the other projects?

**Comment by venezia** [comment]
- Kubernetes uses v - k8s.gcr.io/kube-proxy-amd64:v1.9.
- etcd uses v - https://quay.io/repository/coreos/etcd?tab=tags
- calico uses v - https://quay.io/repository/calico/node?tab=tags

- gitlab does not use v - https://hub.docker.com/r/gitlab/gitlab-ce/tags/
- alpine does not use v - https://hub.docker.com/r/library/alpine/tags/
- ingress-nginx does not use v - quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0

Personally I think we should use v, but that's my opinion.

**Comment by coffeepac** [comment]
I'm in favor of a leading 'v' and filed an issue to modify kraken.  I'll even put it on the shiny new backlog

**Pull request merged**
