### PR TITLE
avoid downloading the full kubernetes release tar for kubectl

### PR DESCRIPTION
**Pull request by spiffxp**

### CODE REVIEW

**Comment by spiffxp** [comment]
ready for a look, but I'd like to keep this PR unmerged for a bit so as to use it to exercise our PR builds

**Comment by spiffxp** [comment]
retest this please

**Comment by alejandroEsc** [comment]
lgtm, (pending retests), nice that this is provided instead of the whole build.

**Comment by maratoid** [comment]
lgtm

**Comment by spiffxp** [comment]
retest this please

**Comment by spiffxp** [comment]
ok, happy enough with 3 passes in a row to call this done

**Pull request merged**
