### PR TITLE
Rename hyperkube_image variable to kubernetes_image_uri for consistency

### PR DESCRIPTION
**Pull request by davidewatson**
with kubernetes_binaries_uri, the default kubernetes deployment method.
(KRAK-407).

### CODE REVIEW

**Comment by davidewatson** [comment]
please retest this

**Comment by davidewatson** [comment]
please retest this

**Comment by spiffxp** [comment]
discussed yesterday, I'm opposed to the term "uri" since google doesn't show it to be idiomatic when referring to docker images

for discoverability we could call it `hyperkube_container_image` to match the `container` deployment mode?  otherwise let's close this out

**Comment by davidewatson** [comment]
After rereading RFC 3986 I am convinced that uri is appropriate, however it is not idiomatic. Since we are refactoring this code now, I propose we close this and name the binary and image identifiers```kubernetes_*``` in the new branch.

**Pull request closed without merging**
