### PR TITLE
[Refactor] Extract k8s version and provider from config file

### PR DESCRIPTION
**Pull request by alejandroEsc**
**What this PR does / why we need it**: In the long term some of this may be deprecated, but for now we need to extract k8s version and provider information from a config file that defines a k8s cluster. We already take in a configuration file, why not extract those values.

If accepted this code will allow us to remove some code from kraken-lib and make less container queries that run ansible

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**: I moved one string output, about which config file being generated to a verbosity option. This cleans outputs of testing and it probably belongs as something in the verbose output anyway.

**Release note**:

```
NONE
```

### CODE REVIEW

**Comment by coffeepac** [comment]
The reason we make a call to the container to fetch the kubernetes version is that all config file parsing gets done in one place.  This means we have one place to update that code if/when the config file changes.

The only deviation we have from this is fetching the cluster name which is:
- a major reason we can't support multiple clusters in a single file
- a hack we need to remove

That said, are there reasons beyond 'code removal in kraken-lib' and 'one fewer container invocation' to merge this?

**Comment by alejandroEsc** [comment]
@coffeepac so the current code in kraken needs to run a script that then runs ansible to extract this information. As you have said, and i agree, this is a bit overkill for what it should do. Should we instead maybe consider using a parser at the level of the container instead of running an ansible script? To be honest this way of doing things, meaning: 

```
[---kraken---]----->[ ---(bridge-code) ----->(ansible script)] 
    go binary                             docker container 
```

is the pattern that lends itself very easily to bugs, mistakes, hard to understand, and less extensible. Here i propose a temporary solution that is only one step and internal to kraken, so we have only one place to parse the config file quickly. We could also extend this code for multiple clusters if the config file has that, so we can definitely make the code more complete. 

I will say that this is temporary, but useful code, and i expect that the full solution is the kraken-config project you mentioned earlier. If you rather i don't mind spear heading that.

Finally this code is just an introduction, it is not connected up yet, that would be the next step.

**Comment by coffeepac** [comment]
with this PR we have one location to parse the config file quickly and one location to parse the config file slowly.  we will need to make sure that both locations stay in sync.   and *for now* its only one the single value:  kubernetes version.  but you're already talking about expanding this to cover kubernetes version for multi-cluster configs and its a very short step to adding other 'single values' to the quick parser.  

and I disagree the current method is buggy.  I believe it is operationally challenging but it creates clear errors when used incorrectly.  however, bugs around config file parsing will result in different parts of the kraken platform having different ideas of what the state of the world should be which may not cause a loud, obvious error.  but may create a situation where the same config file creates different outcomes depending on if the command goes through kraken-lib or stays in kraken.

I am uneasy about this

**Comment by alejandroEsc** [comment]
@coffeepac I think the level of interactions involved is more prone to prone errors than having one stop shop where these bugs can be rectified. Parsing errors, specially in this case can be diminished via tests. However, we dont test the scripts nearly as well as we should if at all. Picking and choosing roles is also subject to errors etc.. 

If you propose now that we open the kraken-config project I would gladly drop this. but if not then i would suggest we simplify code, enforce testing, limit the number of things we do parse (here 3) and move on to the next stage when ready.

Ultimately its your call.

**Comment by alejandroEsc** [comment]
@coffeepac feel free to close out this pr, ill go ahead and start munging some stuff up regarding configs. However, i would like to get the changes associated with the scripts this is trying to replace. preferably before end of today.

**Comment by coffeepac** [comment]
@alejandroEsc sorry I missed this until now, lets talk first thing monday on what you need from me.  I'm pretty stoked you're taking on the config stuff.

**Comment by alejandroEsc** [comment]
@davidewatson i think we should close this after our discussions regarding why this was done, and why we think maybe this isnt the right approach at the moment. Though i disagree with the conclusion im ok with the decision made. So i will close this ticket in lieu on work that I have to plan and get to very soon.

**Pull request closed without merging**
